## Introduction

This project demonstrates the application of NumPy for computation and SciPy for linear algebra operations on two arrays. The focus is on three key areas: general linear algebra operations, permutation techniques, and LU decomposition.

NumPy, a fundamental package for scientific computing in Python, provides powerful tools for array manipulation and basic computations. SciPy's linear algebra module builds upon NumPy, offering specialized routines for advanced linear algebra operations.

In this project, we utilize these libraries to perform:

1. Linear Algebra Operations: Exploring matrix operations, transformations, and solutions to linear systems using SciPy's linear algebra module.

2. Permutation Techniques: Implementing and analyzing various permutation methods on our arrays, showcasing the computational capabilities of NumPy in handling array rearrangements.

3. LU Decomposition: Applying the Lower-Upper (LU) decomposition method to factorize our matrices, demonstrating how this technique can be used to solve linear systems efficiently and compute determinants.

## Objective

- Demonstrate proficiency in using NumPy for computations and SciPy for complex linear algebra operations on two arrays.
- Implement and analyze permutation techniques using NumPy to understand their impact on array manipulation and computation.
- Apply LU decomposition using SciPy's linear algebra module to showcase its utility in solving linear systems and computing determinants.
- Provide a practical example of how these advanced linear algebra techniques can be applied in real-world scientific computing and data analysis scenarios.

In [44]:
#import python libraries
import numpy as np
from scipy.linalg import lu

In [47]:
#declaring variables for matrix A and B using np array
A = np.array([[2,3,4,6],[1,4,5,1],[6,7,8,9],[4,2,9,6]])
B = np.array([[10,12,1,6],[13,2,4,5],[7,8,9,10],[2,4,3,2]])
print( f'Matrix A = \n {A}\n\nMatrix B = \n {B}')

Matrix A = 
 [[2 3 4 6]
 [1 4 5 1]
 [6 7 8 9]
 [4 2 9 6]]

Matrix B = 
 [[10 12  1  6]
 [13  2  4  5]
 [ 7  8  9 10]
 [ 2  4  3  2]]


In [48]:
# Addition of A and B
A+B

array([[12, 15,  5, 12],
       [14,  6,  9,  6],
       [13, 15, 17, 19],
       [ 6,  6, 12,  8]])

In [49]:
# Addition of B and A
B+A

array([[12, 15,  5, 12],
       [14,  6,  9,  6],
       [13, 15, 17, 19],
       [ 6,  6, 12,  8]])

In [50]:
# Substrating B from A
A-B

array([[ -8,  -9,   3,   0],
       [-12,   2,   1,  -4],
       [ -1,  -1,  -1,  -1],
       [  2,  -2,   6,   4]])

In [51]:
# Dividing A by B 
B_inv = np.linalg.inv(B)
np.dot(A, B_inv)
np.round(np.dot(A, B_inv), 4)

array([[ 5.0300e-02, -1.9510e-01,  8.8010e-01, -1.0635e+00],
       [-3.0790e-01,  7.3200e-02, -2.1540e-01,  2.3181e+00],
       [-1.5000e-03, -2.4400e-02,  9.3290e-01, -9.9100e-02],
       [-6.0670e-01,  2.9270e-01,  6.3820e-01,  8.9740e-01]])

In [52]:
# Dividing B by A
A_inv = np.linalg.inv(A)
np.dot(B, A_inv)
np.round(np.dot(B, A_inv), 4)

array([[-3.1076e+00, -6.4570e-01,  3.8688e+00, -1.5879e+00],
       [-5.2651e+00, -2.5906e+00,  3.7743e+00,  8.6880e-01],
       [-1.7060e-01, -2.3600e-02,  1.2310e+00, -5.2000e-03],
       [-2.6250e-01,  4.2520e-01,  5.0920e-01, -2.3880e-01]])

In [53]:
# Multiplication of A, B
A .dot(B)

array([[ 99,  86,  68,  79],
       [ 99,  64,  65,  78],
       [225, 186, 133, 169],
       [141, 148, 111, 136]])

In [54]:
# Multiplication of B, A
B .dot(A)

array([[ 62,  97, 162, 117],
       [ 72,  85, 139, 146],
       [116, 136, 230, 191],
       [ 34,  47,  70,  55]])

In [55]:
# the inverse of A
inverse_A = np.linalg.inv(A)
inverse_A

array([[-0.53805774, -0.22834646,  0.34383202,  0.06036745],
       [ 0.02887139,  0.17322835,  0.0839895 , -0.18372703],
       [ 0.02099738,  0.12598425, -0.12073491,  0.13910761],
       [ 0.3175853 , -0.09448819, -0.07611549, -0.02099738]])

In [56]:
#  the inverse of B
inverse_B = np.linalg.inv(B)
inverse_B

array([[ 0.00609756,  0.09756098, -0.06504065,  0.06300813],
       [ 0.05945122, -0.04878049, -0.05081301,  0.1976626 ],
       [-0.12195122,  0.04878049, -0.03252033,  0.40650407],
       [ 0.05792683, -0.07317073,  0.21544715, -0.56808943]])

In [57]:
# Multipliation of inverse of A, inverse of B
inverse_A .dot(inverse_B)

array([[-0.05529015, -0.02899942,  0.04842306,  0.02643743],
       [-0.01041067,  0.01190705, -0.0529949 ,  0.17457536],
       [ 0.03039978, -0.02016516,  0.02612936, -0.10187941],
       [ 0.00438512,  0.03341655, -0.01790325, -0.01767919]])

In [58]:
# Lu deccomposition of A
lu(A)

(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.16666667,  1.        ,  0.        ,  0.        ],
        [ 0.66666667, -0.94117647,  1.        ,  0.        ],
        [ 0.33333333,  0.23529412,  0.0661157 ,  1.        ]]),
 array([[ 6.        ,  7.        ,  8.        ,  9.        ],
        [ 0.        ,  2.83333333,  3.66666667, -0.5       ],
        [ 0.        ,  0.        ,  7.11764706, -0.47058824],
        [ 0.        ,  0.        ,  0.        ,  3.14876033]]))

In [59]:
# Lu deccomposition of B
lu(B)

(array([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1.        , 0.        , 0.        , 0.        ],
        [0.76923077, 1.        , 0.        , 0.        ],
        [0.53846154, 0.66176471, 1.        , 0.        ],
        [0.15384615, 0.35294118, 0.37924866, 1.        ]]),
 array([[13.        ,  2.        ,  4.        ,  5.        ],
        [ 0.        , 10.46153846, -2.07692308,  2.15384615],
        [ 0.        ,  0.        ,  8.22058824,  5.88235294],
        [ 0.        ,  0.        ,  0.        , -1.76028623]]))

In [60]:
# Pemutation, lower limit and upper limit of A
P1, L1, U1 = lu(A)
print("P1 =\n", L1)
print("L1 =\n", L1)
print("U1 =\n", U1)

P1 =
 [[ 1.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.        ]
 [ 0.66666667 -0.94117647  1.          0.        ]
 [ 0.33333333  0.23529412  0.0661157   1.        ]]
L1 =
 [[ 1.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.        ]
 [ 0.66666667 -0.94117647  1.          0.        ]
 [ 0.33333333  0.23529412  0.0661157   1.        ]]
U1 =
 [[ 6.          7.          8.          9.        ]
 [ 0.          2.83333333  3.66666667 -0.5       ]
 [ 0.          0.          7.11764706 -0.47058824]
 [ 0.          0.          0.          3.14876033]]


In [61]:
# Pemutation, lower limit and upper limit of B
P2, L2, U2 = lu(B)
print("P2 =\n", L1)
print("L2 =\n", L1)
print("U2 =\n", U1)

P2 =
 [[ 1.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.        ]
 [ 0.66666667 -0.94117647  1.          0.        ]
 [ 0.33333333  0.23529412  0.0661157   1.        ]]
L2 =
 [[ 1.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.        ]
 [ 0.66666667 -0.94117647  1.          0.        ]
 [ 0.33333333  0.23529412  0.0661157   1.        ]]
U2 =
 [[ 6.          7.          8.          9.        ]
 [ 0.          2.83333333  3.66666667 -0.5       ]
 [ 0.          0.          7.11764706 -0.47058824]
 [ 0.          0.          0.          3.14876033]]
